### ISSUE TITLE
Personas & User stories

### ISSUE THREAD

**Issue by HumairAK** [operate-first/blueprint#12]
As per our meeting discussions, I think it would be helpful if we considered creating user personas and user stories to gain better insight into the types of users we intend to accommodate. We already have a general understanding of our goals and missions, but this could help organize and categorize those needs onto several archetypes and help drive our decision making. 

Given that our initiative is very contingent upon users using our tooling/docs/repos, this sort of user centered approach could be very beneficial for us.

I can identify at least 2 areas where could potentially benefit from having user personas/stories (you might ave more to add, so definitely open to suggestions): 

- Users of MOC
- Users looking to emulate our setup 

For both of these, I think we can have multiple personas. I was thinking a brief user story for each persona. The user story should be brief, 1-3 lines, and should document practical needs/motivations of the users. Ideally it should also help identify a roadmap for us. 

I would imagine we don't want to go over board here and create  50 different personas, which would not be helpful. So maybe we should try to limit them to about 5-10. 

So having said all that, I would  like to ask you guys: 
- Do you think user personas / stories will be beneficial here? Would you find it useful?

If so then: 
- What would you like to see in such personas/stories? 
- Do you have a specific type of user/goal/need you want captured in such personas/stories? 
- Any thing else you would like to add?

The point of this discussion is to explore this type of user-centered design, gauge everyone's thoughts, and if we're all on board, create new issues to write such personas/userstories.

**Comment by durandom** [comment]
Let's start with the 2 personas we have in our own team. That would be 

* Service Operator 
* Service Consumer

"Service" is a placeholder for every ODH and non-ODH component we're running.

**Comment by durandom** [comment]
How about using a well defined structure for writing the user stories? I remember Cucumber for Behavior Driven Development. This [blog post](https://medium.com/@nic/writing-user-stories-with-gherkin-dda63461b1d2) explains it a bit.

**Comment by durandom** [comment]
cc @goern with https://github.com/operate-first/apps/issues/108

**Comment by HumairAK** [comment]
bump for more discussion

**Comment by tumido** [comment]
I'd add few more personas to consider from top of my head:

- System Integrator
- Platform maintainer (overlaps the Humair's "Users looking to emulate our setup")
- Solution Architect/Technology scout

### System integrator
To me this persona signifies somebody who wants to integrate their application into our setup and make it accessible for our users on clusters managed by us. This persons has to be able to obtain the knowledge and understanding into:
- How our setup works in general so they can verify we are genuine and trustworthy.
- what steps he should take to be included - from namespace and user groups creation and creating ArgoCD apps, to how to structure their application manifests to be able to  deploy everything they have in their repository, in a single step.
- How to provide us their secrets, what communication channels should be used and where they can see their application status, monitoring and stuff and how they, personally can be alerted on their application misbehavior.

### Platform maintainer
I imagine Lars and Ilana to fit in this role. This persona is somebody who can deploy an OCP cluster and wants to get it ready for us, so we can deploy all our applications in there. I'd say this persona has to have access to info about:
- What are the basic needs for us.
- How to grant us the proper access.
- How to deploy our ArgoCD setup in case this is an isolated environment.
- How to attach their cluster to an existing ArgoCD environment in case this new cluster should belong to any existing deployment.

### Solution Architect/Technology scout
This persona is quite the opposite to the ones above. This persona should be able to gain trust in our solution so it can be promoted further. This persona should easily obtain:
- All the information on how we do things and why.
- Can easily grant access to an example deployment as an user in any end user role imaginable.
- Should be able to spin up a dev environment without much previous knowledge - in a "single click deployment" way as possible

**Comment by goern** [comment]
I'd like to add the **Application Owner**, its an extension of the **cloud-native application developer**, this persona would like to try deploying his app and running it, so that he can gather operational experience (which is very different from an integration test) and feed that experience back into the documentation.

**Application Owner**

* all the info to get the application deployed
* all the docs to pass on to the developers, so that could they can deploy the app
* all the source of info required to run the app

**Comment by HumairAK** [comment]
I think our bi-weekly meetings and the issues on this repo (labelled accordingly) are where the future discussions are being held, so closing this in favor of those. Re-open if needed.
