### ISSUE TITLE
What labels to be used to support our workflows on GitHub

### ISSUE THREAD

**Issue by goern** [operate-first/blueprint#27]
SSIA

lets figure out what labels we need for op1st and how they support our workflows. See https://github.com/thoth-station/thoth-application/blob/master/prow/overlays/cnv-prod/labels.yaml and PR against it.

#srcOps 
/sig docs

**Comment by HumairAK** [comment]
Hey @goern , this is new to me, so I have a few questions: 
- Are you suggesting we need a file like this somewhere that organizes the labels prow can apply for each repo? 
- The field `addedBy: anyone` -- what does do for us if it's _not_ prow? Is it just creating the label for that repo?
- The labels that prow applies currently, like "do-not-merge" where are they stored currently? 

I've been creating labels now and then to help us organize our issues, but I've just done this via the UI.

Thanks!

**Comment by HumairAK** [comment]
labels tracked here: https://github.com/operate-first/common with descriptions
