### ISSUE TITLE
CRC vs Quicklab deployments 

### ISSUE THREAD

**Issue by HumairAK** [operate-first/blueprint#28]
I'm seeing little to no difference between crc/quicklab environments, and at this point I wonder if it's worth constantly adding a new directory for both when most of the time they end up being the same (referencing base). Would it not be better to just have a "dev" folder instead? This would reduce a lot of unnecessary clutter. 

If there is a significant between the two (in terms of how/what we deploy), feel free to mention it here -- this is simply what I've noticed :smiley:

**Comment by tumido** [comment]
I don't mind unifying them. I actually agree they both feel more like a dev env than anything else... And I usually end up mixing my own apps/resources combination (I never deploy the defaults) to fit into crc/quicklab, since the cluster size is limited.

**Comment by tumido** [comment]
cc @martinpovolny @anishasthana

**Comment by anishasthana** [comment]
I'm a ++ for this. They have seemed almost identical whenever I did stuff.

**Comment by martinpovolny** [comment]
Yes, makes sense.
