### ISSUE TITLE
Create User Story: I would like to interface a Ceph bucket from my Jupyter notebook

### ISSUE THREAD

**Issue by HumairAK** [operate-first/blueprint#40]

**Comment by 4n4nd** [comment]
@HumairAK @tumido I am having a hard time figuring out what the user has already been given. 
I know the user has access to a Jupyter Notebook environment, but for the Ceph bucket I don't know if they are supposed to request one or should I just assume they have access to a bucket and it's credentials?

**Comment by HumairAK** [comment]
@4n4nd I think we can assume they have one, and have another feature file for the use case of "how to get a bucket" i.e.: https://github.com/operate-first/blueprint/issues/39 -- wdyt?

**Comment by 4n4nd** [comment]
I will assume the user already has access to the secret and configmap generated for the bucket.

**Comment by tumido** [comment]
Yup, I agree, don't bother with creating buckets and getting the creds. That should be handled in the other user story. :+1:
