### ISSUE TITLE
Create User Story: I would like to get my PVC expanded

### ISSUE THREAD

**Issue by tumido** [operate-first/blueprint#42]

**Comment by HumairAK** [comment]
We would like to be more verbose about what persona this feature is targeting, I'd imagine this could be added under the feature description itself.

**Comment by HumairAK** [comment]
The persona for this feature should probably be someone that is part of operate-first JH ops. We may want to consider adding a complimentary user story from a data science perspective whereby this user does not _care about a pvc_ they just want _more space_. This userstory would likely just be about the user creating an issue and when it's closed, the result will be more space for the user.
