### ISSUE TITLE
Decide on a standardized folder structure for storing ci scripts/tools in our repos.

### ISSUE THREAD

**Issue by HumairAK** [operate-first/blueprint#45]
Currently in some repos we're using `hack` folder, is this something we want to continue doing or change it?

**Comment by tumido** [comment]
I don't mind having a `hack` folder. Or we can name it `scripts`. We might also consider using a `.` folder for this so it's hidden from a plain sight maybe (?) and differentiated from the rest of the folders...

**Comment by HumairAK** [comment]
I'm :+1: for `scripts`.

**Comment by anishasthana** [comment]
++ for scripts
