### ISSUE TITLE
Discuss broader end goals for CI and e2e testing for the operate-first initiative.

### ISSUE THREAD

**Issue by HumairAK** [operate-first/blueprint#46]
We had discussions during sprint planning for having a more defined broader goal (or set of goals) when it comes to e2e testing. The purpose of this is to serve as a sort of way to gauge the more granular steps/issues/changes we will be applying and ensuring that they are in line with our broader goals. 

I think we can consider this issue closed if we can answer some of the question: 

What does the ideal e2e scenario look like for operate-first? (e.g. stage/prod clusters, multi step deployments, schema validations, etc.)

Please add your thoughts and other questions that we should be looking to answer.

**Comment by HumairAK** [comment]
Please tag any other interested parties. Thanks.

**Comment by HumairAK** [comment]
@harshad16  @hemajv  @ipolonsk

**Comment by 4n4nd** [comment]
I think ideally, I want to be able to comment `/deploy` on a PR which deploys the PR to a staging/testing cluster

**Comment by anishasthana** [comment]
Having some sort of validation suite for the deployed components would be awesome too.

**Comment by harshad16** [comment]
> I think ideally, I want to be able to comment `/deploy` on a PR which deploys the PR to a staging/testing cluster

with aicoe-ci coupled with argocd, there is `/deploy` option which build & push image and update a desired imagestream to update test cluster. the argocd deploys based on these changes.

we have for the users and it get actively used in thoth and components of opendatahub.
Lets discuss, what would the requirements for e2e test

**Comment by tumido** [comment]
E2E testing via https://github.com/operate-first/SRE/issues/238
