### ISSUE TITLE
Visibility on Collaboration

### ISSUE THREAD

**Issue by anishasthana** [operate-first/blueprint#48]
Hi Folks,

Humair and I were talking earlier today about highlighting visibility into the collaboration we are having between the IDH, Operate First, and ODH teams. I think the engineers on the projects can generally agree that we have a good amount of shared development efforts and knowledge sharing but it is hard to quantifiably state that. Does anyone here have any ideas on improving visibility on this?  

It'd be cool if there was some existing tool that lets you see interactions between organizations on Github, but a cursory google search didn't seem to surface anything. 

cc @HumairAK @tumido @4n4nd @durandom @vpavlin @accorvin

**Comment by HumairAK** [comment]
I think for the most part, folks have been pretty good at linking to and fro from Operate-First repositories, so the information is certainly there and can/should be retrievable via github api for example. We would just need a way to aggregate/collect and present it in a fashion that is easier to consume.

**Comment by accorvin** [comment]
I think this is an important problem to solve, but also a challenging one and one that I don't have any great ideas for how to fix.

We could certainly write some scripts to measure contributions on pull requests and issues and that sort of thing, but...
![giphy](https://user-images.githubusercontent.com/5041129/110962142-9fe87000-831e-11eb-84bc-58e4f8dc5dc0.gif)

What would people thing of try to start some demo sessions where we show off to each other what we've been working on?
