### ISSUE TITLE
Change default branches to main

### ISSUE THREAD

**Issue by anishasthana** [operate-first/blueprint#50]
Hey!

More and more open source projects are changing their default branches to be `main` instead of `master`. New repositories on Github already default to main, and Gitlab will soon be doing the same. Should we consider changing the defaults on operate-first repositories as well?

**Comment by HumairAK** [comment]
Yes, I think we should adapt to the new standard and update our default branches to `main`.

**Comment by anishasthana** [comment]
What's a good plan of action? Create issues on all repositories and slowly port them over?

**Comment by HumairAK** [comment]
I'd rather just create one issue with a checklist for all repos. Off the top of my head, some of the kfdefs will need to be updated and any links in docs throughout the org. And down stream repos linking via remote references (aicoe-cd comes to mind). Shouldn't be too bad imo.

**Comment by anishasthana** [comment]
I'm good with that, should I just add a checklist to this issue? or create a new one in the blueprints repo?

**Comment by tumido** [comment]
Currently we have a mix of `main` and `master` branches in our repos. I think it would be nice to unify it. :+1: 

I think we can add the checklist to this issue. There's no point to have multiple issues for the same task.

Additional points to @HumairAK's:
- [ ] Change [Travis build config](https://github.com/operate-first/operate-first.github.io/blob/master/.travis.yml) for the website
- [ ] Update [`srcLink`](https://github.com/operate-first/operate-first.github.io/blob/a7d9e652a3a5634223892f89b5fa695e9a7710c1/gatsby-node.js#L41-L45) for Gatsby nodes for the website

**Comment by anishasthana** [comment]
I came up with the following checklist -- wdyt?
- [ ] apps
  - [ ]  Update kfdefs to point to correct repositories
- [ ] SRE
- [ ] operate-first.github.io
- [x] support
- [x] argocd-apps
- [x] workshop-apps
- [ ] continuous-deployment
  - [ ]  Update remote references in downstream aicoe-cd repository
- [x] blueprint
- [ ] toolbox
- [ ] continuous-delivery
- [ ] odh-dashboard
- [ ] Change [Travis build config](https://github.com/operate-first/operate-first.github.io/blob/master/.travis.yml) for the website
- [ ] Update `[srcLink](https://github.com/operate-first/operate-first.github.io/blob/a7d9e652a3a5634223892f89b5fa695e9a7710c1/gatsby-node.js#L41-L45)` for Gatsby nodes for the website
- [ ] Update links in the docs websites to new locations
- [ ] `continuous-deployment`'s remote reference for [apps of apps](https://github.com/operate-first/continuous-deployment/pull/137/files#diff-9e11eaf0af11db46be62c85549bc6ebcfde709297d946e61b22e285689007315R4)

**Comment by tumido** [comment]
`support`, `blueprint`, `workshop-apps`, and `argocd-apps` repos already use `main` as the default branch, those points are invalid

**Comment by anishasthana** [comment]
nice! 4 items on the checklist can already be checked off :-D

**Comment by larsks** [comment]
Is there anything preventing us from just renaming the default branch on the `apps` repository? It looks as if all the configurations that point there are using `HEAD`, so they should follow the change without a problem.

**Comment by HumairAK** [comment]
@larsks -- yes some of the files [here](https://github.com/operate-first/apps/search?p=1&q=filename%3Akfdef.yaml) will need to be updated, as they reference the app repo itself for odh manifests. [Example](https://github.com/operate-first/apps/blob/1b042ed6650f069f2ed0aabe69d1250488897afb/odh/base/jupyterhub/kfdef.yaml#L40).

**Comment by tumido** [comment]
Added `continuous-deployment`'s remote reference for [apps of apps](https://github.com/operate-first/continuous-deployment/pull/137/files#diff-9e11eaf0af11db46be62c85549bc6ebcfde709297d946e61b22e285689007315R4) to the list
