### ISSUE TITLE
Discuss ideas for grafana dashboard collaboration 

### ISSUE THREAD

**Issue by HumairAK** [operate-first/blueprint#53]
Discuss ideas for grafana dashboard collaboration (opf, RHODS, upstream ODH). We need to have a single source of truth for the grafana dashboards being developed across our teams.

**Comment by accorvin** [comment]
How does the operate first team currently create Grafana dashboards? Looking at https://github.com/operate-first/SRE/tree/master/dashboards it appears that it may be a manual process of applying JSON definitions from Git?

**Comment by 4n4nd** [comment]
@accorvin we have GrafanaDashboard resources in the apps repo ([link](https://github.com/operate-first/apps/blob/master/odh/overlays/moc/zero/monitoring/dashboards/operate-first/jupyterhub-usage.yaml#L9)) where we link these jsons directly.

These GrafanaDashboard manifests are then picked up by the grafana operator.

**Comment by anishasthana** [comment]
That actually greatly simplifies the ODH + OPF collaboration piece. We can just have these dashboard jsons exist in a directory in upstream ODH.

**Comment by accorvin** [comment]
Yep, I think this makes things way easier than we thought they might be.

@anishasthana it looks like we put the JSON as the body of a configmap. Presumably we need to figure out how to import the JSON from a different file into the configmap?

**Comment by anishasthana** [comment]
Yep, that sounds about right.

**Comment by accorvin** [comment]
@anishasthana do you have ideas for how to do that? Is this just kustomize-fu?

**Comment by tumido** [comment]
@anishasthana @accorvin if you want to import any file into a configmap you can use the `configMapGenerator` in kustomize. So.. only some kustomize-fu. :smile: 

https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/configmapgenerator/

**Comment by anishasthana** [comment]
I can take a stab at it when I have some free time. This shouldn't be bad at all. @maulikjs was already thinking of adding some kustomize to our deploy scripts.

**Comment by hemajv** [comment]
> That actually greatly simplifies the ODH + OPF collaboration piece. We can just have these dashboard jsons exist in a directory in upstream ODH.

Yes, we have a PR open here: https://github.com/opendatahub-io/odh-manifests/pull/316 for adding JupyterHub monitoring dashboards. In this PR, we are adding the JSONs into a separate `/dashboards` folder. Once this is merged, we can go ahead and remove the jsons from our SRE repo ([link](https://github.com/operate-first/SRE/tree/master/dashboards)) and update the url in our GrafanaDashboard resources to point to these jsons.

**Comment by tumido** [comment]
@hemajv I'm not sure if dashboards hidden within `grafana/grafana/base/dashboards/` path in https://github.com/opendatahub-io/odh-manifests repo is a solution that is "observable" enough. I think a standalone repository for community managed dashboards would draw much more attention and bring more collaboration. People interested in dashboards won't subscribe to odh-manifests repo.

**Comment by hemajv** [comment]
@tumido definitely, I think that is a good idea! I'm a +1 for having a separate repo dedicated to dashboards and placing all JSONs there, would like to know others thoughts on it as well. Also, where do you think would be a good place for this repo?

**Comment by anishasthana** [comment]
That's a good question. I wonder if @LaVLaS  has some thoughts here.

**Comment by tumido** [comment]
@hemajv I don't mind hosting it in Operate First, since it's more SRE and Ops focused org. - I'd be glad to support it and open it up to community.

A separate repo in ODH upstream is also a good place, if they have a strong opinion to host it. In the end I don't mind the location that much...

**Comment by accorvin** [comment]
I'd prefer if the ODH monitoring artifacts went in an ODH repo.

**Comment by maulikjs** [comment]
We should also publish these dashboards that we come up with here: https://grafana.com/grafana/dashboards
9/10 times I look for a dashboard there before anywhere else or making one myself, and there will definitely be some gaps around JH, OCP, etc that we could fill, especially for SREs.

**Comment by LaVLaS** [comment]
> I'd prefer if the ODH monitoring artifacts went in an ODH repo.

In ODH, it would be great if there was one, version pinned, default dashboard per component. Ideally we would store the JSON in the `GrafanaDashboard` resource so that the dashboard is pinned to the component version in the release. 

For advanced dashboard, could we just add an `operate-first` overlay in ODH grafana that would supply advanced dashboard hosted by `operate-first`?

**Comment by anishasthana** [comment]
I'm not a huge fan of that, Ideally we keep pulling in experience from IDH/Operate-first to benefit upstream dashboards and alerts.

**Comment by tumido** [comment]
@anishasthana does that mean we would limit this collaboration to dashboards about ODH components only? What about other Operate First dashboards we'd like share? Like.. AiCoE-CI dashboards from Thoth or Observatorium monitoring and so on.

I'd like to see open community around this. If stored in ODH, it means we're limiting it to ODH related deployments only. I think we Operate First tried to go beyond ODH and include and understand more workloads than that.

**Comment by anishasthana** [comment]
I'm not sure I see a problem with having a mix? Anything that's not ODH specific (thingsl ike thoth or observatorium) can reside in the operate-first SRE repo, but  for ODH dashboards we can just point to the upstream ones.

**Comment by 4n4nd** [comment]
> we would store the JSON in the `GrafanaDashboard` resource so that the dashboard is pinned to the component version in the release

@LaVLaS  I think you can just use a url to a fixed version instead.
For example: Instead of using 
```
https://raw.githubusercontent.com/hemajv/odh-manifests/add-jh-dashboards/grafana/grafana/base/dashboards/jupyterhub-sli-slo.json
```
we can use 
```
https://raw.githubusercontent.com/hemajv/odh-manifests/9c6425642121f8fbe986e024a7886c7287430d33/grafana/grafana/base/dashboards/jupyterhub-sli-slo.json```

**Comment by durandom** [comment]
I second what @maulikjs said, the op1st community and odh community should publish their dashboards to grafana too.

Once we have a larger set of dashboards, we can think about a good place to host them and/or create a dedicated repo. 
For now let's figure out the re-use of existing dashboards first  :)

**Comment by HumairAK** [comment]
@hemajv can you sum up  briefly the online/offline discussions with the consensus that we reached.

**Comment by LaVLaS** [comment]
Quick summary: In ODH the `GrafanaDashboard` object and dashboard `json` will be separated into the customresource and a raw json file that will be reference from a `ConfigMap` that is created by the `kustomize` `ConfigMapGenerator`. This will allow ODH to host the static object in a single commit while still allowing remote references/overlays of the individual dashboard json

**Comment by HumairAK** [comment]
Okay great, it is my understanding everyone is agreed on the summary provided by @LaVLaS. Therefore, I think the thread has served it's purpose. Closing, feel free to open if there's more left to discuss.
