### ISSUE TITLE
ADR for EULA

### ISSUE THREAD

**Issue by durandom** [operate-first/blueprint#76]
We need a [EULA](https://en.wikipedia.org/wiki/End-user_license_agreement) for accessing the environment

We don't want consumers of the operational data sign a EULA for accessing the data, but the data should be published under an open source license

related PRs #75 #74

**Comment by billburnseh** [comment]
Will add this to my question to RH legal to see if there are known agreements like this.

**Comment by billburnseh** [comment]
Current thinking is that an existing AUP (Acceptable Use Policy, like a EULA) should cover data access within the environment, with possible additions specific to data access. Further, there could be a separate data access policy, but that is unclear at this time. Moving data outside the environment to make it. Current doc working the issues is at  https://docs.google.com/document/d/1j8pVhN6n-8xuQpoPpsZS4fWnmGuNPxBMsIWUvzxg99o/edit?usp=sharing

**Comment by billburnseh** [comment]
Still not clear if the existing AUP may need a tweak to note data access within the operate first environment., but may be fine as is. Will get final info when Michael Daitzman returns from vacation.

**Comment by billburnseh** [comment]
BU's office of tech development contact just back from vacation. Discussions resumed this week on any changes to AUO (EULA) and a data agreement.

**Comment by billburnseh** [comment]
No updates from BU yet.

**Comment by billburnseh** [comment]
No update on this, but the larger issue, a Data Usage Agreement (DUA) is on the table and being discussed, including access to telemetry without anonymization.

**Comment by billburnseh** [comment]
As of Oct 21, 2021, BU is in discussion with Harvard on language for a modified EULA and plans to share the outcome more widely as soon as possible thereafter.
