### ISSUE TITLE
ADR for data license

### ISSUE THREAD

**Issue by durandom** [operate-first/blueprint#77]
We want to publish all collected data under an open source license.
Decide which one to use.

related issue #76

**Comment by billburnseh** [comment]
Do we have a list of preferred licenses? I will ping Red Hat legal to get input from that angle.

**Comment by hpdempsey** [comment]
> Do we have a list of preferred licenses? I will ping Red Hat legal to get input from that angle.

GNU GPL was selected for the code, so that's certainly an argument to keep it for simplicity.  See https://github.com/operate-first/blueprint/blob/main/docs/adr/0001-use-gpl3-as-license.md
@billburnseh

**Comment by durandom** [comment]
I'm not sure if we can use a code license for data.

These two are more geared towards data:

* https://github.com/lfai/CDLA 
* CC0 https://creativecommons.org/publicdomain/zero/1.0/legalcode

**Comment by tumido** [comment]
Valid point.

[ODBL](https://opendatacommons.org/licenses/odbl/summary/) seams reasonable as well, it's used by OpenStreetMaps - they also have this neat compatibility table: https://wiki.openstreetmap.org/wiki/Import/ODbL_Compatibility
That may give us some ideas... :slightly_smiling_face:

**Comment by billburnseh** [comment]
Work is progressing on the access to data. BU has a document to summarize which will lead to addressing any AUP or data access agreements that are needed/ Doc is located here: https://docs.google.com/document/d/1j8pVhN6n-8xuQpoPpsZS4fWnmGuNPxBMsIWUvzxg99o/edit?usp=sharing. Note that the initial work is focused on access within the environment and the topic of a fully open repo requires further definition of the data, and mitigation required to scrub inforation that could be used in violation of various data protection laws around PII (Personally Identifyable Information) such as GPDR.
Resolution of this aspect is not expected soon.

**Comment by billburnseh** [comment]
Work continues on this, lead by Orran at BU. His last update on 5/28 "Very positive initial feedback from office of technology development, so now we just need to iron out the contract for the DUA and the notice to users, and then work on each of the specific logs… we want to de-identify."

**Comment by billburnseh** [comment]
BU's office of tech development contact just back from vacation. Discussions resumed this week on any changes to AUO (EULA) and a data agreement.

**Comment by billburnseh** [comment]
No updates from BU yet.

**Comment by billburnseh** [comment]
No update on this, but the larger issue, a Data Usage Agreement (DUA) is on the table and being discussed, including access to telemetry without anonymization.
