### ISSUE TITLE
Definition of the most open environment

### ISSUE THREAD

**Issue by durandom** [operate-first/blueprint#78]
We'll have environments that are connected to universities, as they're hosted in a university data center. Here the university superimposes legal requirements.

But we'll also have environments that are located in EMEA on-premise datacenters, such as the Hetzner setup.
How can we create an environment that is as open as possible?

One of the key components of a true public Operate First capability for open source communities is going to be the legal framework that governs the data.

1. grant public read-only access to all platform- and (potentially) workload configuration (excl. secrets) - think browsing open-source code
2. grant public read-only access to all platform- and (potentially) workload operational data (logs, metrics, issues) without the need to scrub the data  - think browsing open-source code
3. grant authenticated read-write access to the environment with the least legal hurdles - e.g. by accessing you're accepting a EULA implicitly - think deploying workloads

We don't want to constrain how the data is accessed, i.e. people with access to the data might implicitly accept an agreement, best we want to make it available to the world so that no authentication is in place and even a web-search-crawler could access it.
The technical implementation is straightforward. But we have to stay within legal requirements, like GDPR.

The legal question would be: what are the agreements/licenses/etc we need to put in place and what is the nature of the data we're allowed to publish

The definition of operational data is tracked in https://github.com/operate-first/blueprint/issues/80

**Comment by billburnseh** [comment]
This issues is under active work by our friends at BU with an eye toward crafting agreements that will be usable in other places beyond BU.
