### ISSUE TITLE
RFE ApplicationSets and Directory Structre

### ISSUE THREAD

**Issue by christianh814** [operate-first/blueprint#85]
Sections "ArgoCD App of Apps" needs to be rethought since ApplicationSets aims to solve this "bootstrapping" issue. Also, working with ApplicationSets will give you a new outlook on directory structure.

Will be happy to work with anyone to get this together.

**Comment by HumairAK** [comment]
Hello @christianh814 this is something we are considering since the update to 2.0.1, we have a thread already going for this [here](https://github.com/operate-first/apps/issues/502)

Going to close this thread as this is a duplicate, we welcome your thoughts in the thread linked above..
