### ISSUE TITLE
[yamllint] Document start settings

### ISSUE THREAD

**Issue by tumido** [operate-first/blueprint#89]
The question is, should we enforce `---` document starts on YAML files or not?

This appeared here: https://github.com/operate-first/apps/pull/628#issuecomment-839934760
Attempt to solve this: https://github.com/operate-first/apps/pull/639

I think this deserves a proper issue, rather than a few chat messages.

For enforcing:
- [Part of the standard](https://yaml.org/spec/1.2/spec.html#id2800132)
- Less opinionated yamllint config (using [default values](https://yamllint.readthedocs.io/en/stable/configuration.html#default-configuration))
- We can `cat` multiple files if needed and docs are properly separated
- Single YAML doc files are consistent with multidoc files

Against enforcing:
- It's just clutter in most cases
- Too verbose for single doc YAML files

Note: This change doesn't affect the `apps` repo only. It should be enforced equally on all repos across this organization.

**Comment by HumairAK** [comment]
I don't have a strong preference, @tumido do you?

**Comment by tumido** [comment]
My preference is always to stick with the standards if we don't have any strong argument against - staying as non-opinionated as possible sounds like the key to openness to me.

Also non-opinionated != lazy. :grin:

**Comment by HumairAK** [comment]
Sounds good, since we already enforce it I'm closing this thread -- please re open if there's more.

**Comment by larsks** [comment]
> Sounds good, since we already enforce it...

To be clear, we explicitly don't enforce it:

```
document-start: disable
```

That means "we don't care". Which is fine :).

**Comment by tumido** [comment]
> That means "we don't care". Which is fine :).

Haha, I like that :smile: :+1:
