### ISSUE TITLE
ADR: on Storage and IPSec

### ISSUE THREAD

**Issue by goern** [operate-first/blueprint#91]
We need to figure out how we design/deploy a private network on public interfaces, and how to deploy storage

@tumido @rbo

**Comment by tumido** [comment]
:+1: I have no knowledge on this topic, so my input will be probably minimal, but I agree with the need for this in general. :slightly_smiling_face:

**Comment by goern** [comment]
Rober got all the brains, you got all the process/docs ;) I use the words of a well-known person: its a win-win-win situation

**Comment by rbo** [comment]
Currently, the SDN traffic is plain is unencrypted over public ips, it stays in the Hetzner datacenter but is unencrypted!

The Solution is to setup IPSec between all nodes: https://docs.openshift.com/container-platform/4.7/installing/installing_bare_metal/installing-bare-metal-network-customizations.html#modifying-nwoperator-config-startup_installing-bare-metal-network-customizations

Overview:

![image](https://user-images.githubusercontent.com/36604/118952951-ac132e00-b95c-11eb-981e-6650aded52c2.png)

Import the part "**The following internode traffic is NOT IPSec encrypted:**" to understand the limitation.
