### ISSUE TITLE
ADR vs ART prefixes in the readme page

### ISSUE THREAD

**Issue by HumairAK** [operate-first/blueprint#97]
@margarethaley brought up that the index page [here](https://github.com/operate-first/blueprint/blob/main/README.md) has either the `ADR-*` prefix or `ART-*` prefix. I have no idea what ART is, seems like a typo to me that just propagated. Anyone else happen to know?

**Comment by tumido** [comment]
lol.. I think that's a typo.. I don't think it should say `ART`. Seems like an easy fix, right? https://github.com/operate-first/blueprint/pull/98
